FROM alpine:3.18@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="retry"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/retry"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/retry"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/retry"

ADD retry /usr/local/bin/retry

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/retry"]
