FROM alpine:3.17@sha256:c8deccde20bcc319a17c28ce674b80b9b7e945a8b460a11272b7f0a3e0d6a746

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="retry"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/retry"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/retry"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/retry"

ADD retry /usr/local/bin/retry

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/retry"]
