FROM arm64v8/alpine:3.16@sha256:d66d8a4b754d1e4da73ed711f0df63b3f19403f4e0711e4edc97ac87d20d707a

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="retry"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/retry"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/retry"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/retry"

ADD retry /usr/local/bin/retry

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/retry"]
