FROM arm64v8/alpine:3.16@sha256:ed73e2bee79b3428995b16fce4221fc715a849152f364929cdccdc83db5f3d5c

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="retry"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/retry"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/retry"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/retry"

ADD retry /usr/local/bin/retry

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/retry"]
