---
when:
  - ref: refs/heads/main
  - ref: refs/tags/**
  - ref: refs/pull/**

steps:
  dryrun:
    image: quay.io/thegeeklab/drone-docker-buildx:23
    settings:
      dockerfile: Dockerfile.multiarch
      dry_run: true
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
        - linux/arm/v6
      provenance: false
      repo: thegeeklab/${CI_REPO_NAME}
    when:
      - ref: refs/pull/**

  publish-dockerhub:
    group: build
    image: quay.io/thegeeklab/drone-docker-buildx:23
    settings:
      auto_tag: true
      dockerfile: Dockerfile.multiarch
      password:
        from_secret: docker_password
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
        - linux/arm/v6
      provenance: false
      repo: thegeeklab/${CI_REPO_NAME}
      username:
        from_secret: docker_username
    when:
      - ref: refs/heads/main
      - ref: refs/tags/**

  publish-quay:
    group: build
    image: quay.io/thegeeklab/drone-docker-buildx:23
    settings:
      auto_tag: true
      dockerfile: Dockerfile.multiarch
      password:
        from_secret: quay_password
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
        - linux/arm/v6
      provenance: false
      registry: quay.io
      repo: quay.io/thegeeklab/${CI_REPO_NAME}
      username:
        from_secret: quay_username
    when:
      - ref: refs/heads/main
      - ref: refs/tags/**

depends_on:
  - test
