---
when:
  - event:
      - tag
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
runs_on:
  - success
  - failure

steps:
  matrix:
    image: quay.io/thegeeklab/drone-matrix
    settings:
      homeserver:
        from_secret: matrix_homeserver
      password:
        from_secret: matrix_password
      roomid:
        from_secret: matrix_roomid
      template: "Status: **{{ .Build.Status }}**<br/> Build: [{{ .Repo.Owner }}/{{ .Repo.Name }}]({{ .Build.Link }}){{ if .Build.Branch }} ({{ .Build.Branch }}){{ end }} by {{ .Commit.Author }}<br/> Message: {{ .Commit.Message.Title }}"
      username:
        from_secret: matrix_username
    when:
      - status:
        - success
        - failure

depends_on:
  - test
  - container
  - release
