---
when:
  - ref: refs/heads/${CI_REPO_DEFAULT_BRANCH}
  - ref: refs/tags/**
  - ref: refs/pull/**

steps:
  checksum:
    image: docker.io/alpine
    commands:
      - sha256sum retry > sha256sum.txt

  changelog-generate:
    image: quay.io/thegeeklab/git-chglog
    commands:
      - git fetch -tq
      - git-chglog --no-color --no-emoji -o CHANGELOG.md ${CI_COMMIT_TAG:---next-tag unreleased unreleased}

  changelog-format:
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - prettier CHANGELOG.md
      - prettier -w CHANGELOG.md

  publish-github:
    image: docker.io/plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - retry
        - sha256sum.txt
      note: CHANGELOG.md
      overwrite: true
      title: ${CI_COMMIT_TAG}
    when:
      - ref: refs/tags/**

depends_on:
  - test
