---
when:
  - event:
      - pull_request
      - tag
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  lint:
    group: test
    image: docker.io/koalaman/shellcheck-alpine:stable
    commands:
      - shellcheck ./retry

  test:
    group: test
    image: docker.io/bats/bats
    commands:
      - bats ./retry.bats
