---
when:
  - ref: refs/heads/main
  - ref: refs/tags/**
  - ref: refs/pull/**

steps:
  lint:
    group: test
    image: docker.io/koalaman/shellcheck-alpine:stable
    commands:
      - shellcheck ./retry

  test:
    group: test
    image: docker.io/bats/bats
    commands:
      - bats ./retry.bats
