---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: test
    image: docker.io/bats/bats
    depends_on: []
    commands:
      - bats ./retry.bats
